# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-color: rgb(71, 98, 104);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -20, 391, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("linkedin_banner_image_2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btn_Cadastrar = QtWidgets.QPushButton(Form)
        self.btn_Cadastrar.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.btn_Cadastrar.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_Cadastrar.setObjectName("btn_Cadastrar")
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.btn_login.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_login.setObjectName("btn_login")
        self.line_senha = QtWidgets.QLineEdit(Form)
        self.line_senha.setGeometry(QtCore.QRect(110, 160, 170, 35))
        self.line_senha.setMinimumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_senha.setFont(font)
        self.line_senha.setStyleSheet("border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.line_senha.setObjectName("line_senha")
        self.line_login = QtWidgets.QLineEdit(Form)
        self.line_login.setGeometry(QtCore.QRect(110, 115, 170, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_login.setFont(font)
        self.line_login.setStyleSheet("border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_login.setText("")
        self.line_login.setFrame(True)
        self.line_login.setAlignment(QtCore.Qt.AlignCenter)
        self.line_login.setDragEnabled(False)
        self.line_login.setReadOnly(False)
        self.line_login.setObjectName("line_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_Cadastrar.setText(_translate("Form", "Cadastrar"))
        self.btn_login.setText(_translate("Form", "Login"))
        self.line_senha.setPlaceholderText(_translate("Form", "Senha"))
        self.line_login.setPlaceholderText(_translate("Form", "Usuario"))
