# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_transferir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_transferencia(object):
    def setupUi(self, tela_transferencia):
        tela_transferencia.setObjectName("tela_transferencia")
        tela_transferencia.resize(400, 301)
        tela_transferencia.setStyleSheet("background-color: rgb(71, 98, 104);")
        self.label = QtWidgets.QLabel(tela_transferencia)
        self.label.setGeometry(QtCore.QRect(1, -40, 390, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("linkedin_banner_image_2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.line_input_valor = QtWidgets.QLineEdit(tela_transferencia)
        self.line_input_valor.setGeometry(QtCore.QRect(105, 170, 200, 30))
        self.line_input_valor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 8pt \"Arial Black\";\n"
"")
        self.line_input_valor.setText("")
        self.line_input_valor.setObjectName("line_input_valor")
        self.btn_transferir = QtWidgets.QPushButton(tela_transferencia)
        self.btn_transferir.setGeometry(QtCore.QRect(100, 215, 85, 23))
        self.btn_transferir.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.btn_transferir.setObjectName("btn_transferir")
        self.btn_sair = QtWidgets.QPushButton(tela_transferencia)
        self.btn_sair.setGeometry(QtCore.QRect(220, 215, 85, 23))
        self.btn_sair.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.btn_sair.setObjectName("btn_sair")
        self.line_input_destinatario = QtWidgets.QLineEdit(tela_transferencia)
        self.line_input_destinatario.setGeometry(QtCore.QRect(80, 130, 261, 31))
        self.line_input_destinatario.setMaximumSize(QtCore.QSize(261, 31))
        self.line_input_destinatario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 87 8pt \"Arial Black\";\n"
"font: 87 8pt \"Arial Black\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_input_destinatario.setText("")
        self.line_input_destinatario.setObjectName("line_input_destinatario")
        self.label_saldo = QtWidgets.QLabel(tela_transferencia)
        self.label_saldo.setGeometry(QtCore.QRect(265, 20, 130, 35))
        self.label_saldo.setStyleSheet("font: 87 9pt \"Arial Black\";\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.label_saldo.setText("")
        self.label_saldo.setObjectName("label_saldo")
        self.label_conta_2 = QtWidgets.QLabel(tela_transferencia)
        self.label_conta_2.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.label_conta_2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"font: 87 8pt \"Arial Black\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.label_conta_2.setText("")
        self.label_conta_2.setObjectName("label_conta_2")
        self.label_nome = QtWidgets.QLabel(tela_transferencia)
        self.label_nome.setGeometry(QtCore.QRect(10, 10, 145, 20))
        self.label_nome.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.label_nome.setText("")
        self.label_nome.setObjectName("label_nome")
        self.label_idade = QtWidgets.QLabel(tela_transferencia)
        self.label_idade.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.label_idade.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"font: 87 8pt \"Arial Black\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.label_idade.setText("")
        self.label_idade.setObjectName("label_idade")

        self.retranslateUi(tela_transferencia)
        QtCore.QMetaObject.connectSlotsByName(tela_transferencia)

    def retranslateUi(self, tela_transferencia):
        _translate = QtCore.QCoreApplication.translate
        tela_transferencia.setWindowTitle(_translate("tela_transferencia", "Form"))
        self.line_input_valor.setPlaceholderText(_translate("tela_transferencia", "             Digite o Valor"))
        self.btn_transferir.setText(_translate("tela_transferencia", "Transferir"))
        self.btn_sair.setText(_translate("tela_transferencia", "sair"))
        self.line_input_destinatario.setPlaceholderText(_translate("tela_transferencia", "                Digite o Destinatário"))
