# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_de_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastro_tela(object):
    def setupUi(self, cadastro_tela):
        cadastro_tela.setObjectName("cadastro_tela")
        cadastro_tela.resize(400, 300)
        cadastro_tela.setStyleSheet("background-color: rgb(71, 98, 104);")
        self.verticalLayoutWidget = QtWidgets.QWidget(cadastro_tela)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 50, 251, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_nome = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_nome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_nome.setText("")
        self.line_nome.setObjectName("line_nome")
        self.verticalLayout.addWidget(self.line_nome)
        self.line_sobrenome = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_sobrenome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_sobrenome.setObjectName("line_sobrenome")
        self.verticalLayout.addWidget(self.line_sobrenome)
        self.line_idade = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_idade.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_idade.setObjectName("line_idade")
        self.verticalLayout.addWidget(self.line_idade)
        self.line_cadastrar_login = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_cadastrar_login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_cadastrar_login.setObjectName("line_cadastrar_login")
        self.verticalLayout.addWidget(self.line_cadastrar_login)
        self.line_cadastrar_senha = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_cadastrar_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.line_cadastrar_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_cadastrar_senha.setObjectName("line_cadastrar_senha")
        self.verticalLayout.addWidget(self.line_cadastrar_senha)
        self.btn_enviar_cadastro = QtWidgets.QPushButton(cadastro_tela)
        self.btn_enviar_cadastro.setGeometry(QtCore.QRect(280, 250, 75, 23))
        self.btn_enviar_cadastro.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_enviar_cadastro.setObjectName("btn_enviar_cadastro")
        self.label = QtWidgets.QLabel(cadastro_tela)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 310))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("facebook_profile_image.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(cadastro_tela)
        self.label_2.setGeometry(QtCore.QRect(47, 7, 300, 40))
        self.label_2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(95, 133, 140);\n"
"font: 87 8pt \"Arial Black\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.btn_enviar_cadastro.raise_()
        self.label_2.raise_()

        self.retranslateUi(cadastro_tela)
        QtCore.QMetaObject.connectSlotsByName(cadastro_tela)

    def retranslateUi(self, cadastro_tela):
        _translate = QtCore.QCoreApplication.translate
        cadastro_tela.setWindowTitle(_translate("cadastro_tela", "Form"))
        self.line_nome.setPlaceholderText(_translate("cadastro_tela", "Nome"))
        self.line_sobrenome.setPlaceholderText(_translate("cadastro_tela", "Sobrenome"))
        self.line_idade.setPlaceholderText(_translate("cadastro_tela", "Idade"))
        self.line_cadastrar_login.setPlaceholderText(_translate("cadastro_tela", "Loguin"))
        self.line_cadastrar_senha.setPlaceholderText(_translate("cadastro_tela", "Senha"))
        self.btn_enviar_cadastro.setText(_translate("cadastro_tela", "Enviar"))
